In [2]:
import os
import sys

# Import Code modules
module_path = os.path.abspath(os.path.join('../code'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [14]:
# Con'd import
from data_fetcher import DataFetcher
from endpoint_type import EndpointType
from db_connector import DBConnector
from flusurv_params import *
from fluview_params import *
from gft_params import *

db_connector = DBConnector()

In [12]:
flusurv_param = FluSurvParams(
    epiweeks = ["202003", "202004"], 
    regions = [FluSurvRegion.CA, FluSurvRegion.CO, FluSurvRegion.IA]
)

DataFetcher.fetch(EndpointType.FLUSURV, param=flusurv_param)

  release_date location   issue  ...  rate_age_3  rate_age_4  rate_overall
0   2020-11-06       CA  202044  ...         5.2        12.0           4.4
1   2020-11-06       CO  202044  ...         6.1         6.4           4.0
2   2020-11-06       CA  202044  ...         5.5        17.6           4.9
3   2020-11-06       CO  202044  ...         6.7        14.5           4.9

[4 rows x 11 columns]

In [15]:
query = f"""
select * from {DBConnector.resolveTableName(EndpointType.FLUSURV)}
group by location
"""

db_connector.read(query)

  release_date location   issue  ...  rate_age_3  rate_age_4  rate_overall
0   2020-11-06       CA  202044  ...         5.2        12.0           4.4
1   2020-11-06       CO  202044  ...         6.1         6.4           4.0

[2 rows x 11 columns]